#load @"include.system.collections.fsx" 
#load @"include.system.diagnostics.debug.fsx" 
#load @"include.system.diagnostics.tools.fsx" 
#load @"include.system.globalization.fsx" 
#load @"include.system.io.fsx" 
#load @"include.system.reflection.fsx" 
#load @"include.system.resources.resourcemanager.fsx" 
#load @"include.system.runtime.fsx" 
#load @"include.system.runtime.extensions.fsx" 
#load @"include.system.text.encoding.fsx" 
#load @"include.system.threading.fsx" 
#load @"include.system.xml.readerwriter.fsx" 
#r "System.Xml.Linq" 
printfn "system.xml.xdocument Loaded" 