#load @"include.system.collections.fsx" 
#load @"include.system.diagnostics.debug.fsx" 
#load @"include.system.dynamic.runtime.fsx" 
#load @"include.system.globalization.fsx" 
#load @"include.system.linq.fsx" 
#load @"include.system.linq.expressions.fsx" 
#load @"include.system.objectmodel.fsx" 
#load @"include.system.reflection.fsx" 
#load @"include.system.reflection.extensions.fsx" 
#load @"include.system.reflection.primitives.fsx" 
#load @"include.system.reflection.typeextensions.fsx" 
#load @"include.system.resources.resourcemanager.fsx" 
#load @"include.system.runtime.fsx" 
#load @"include.system.runtime.extensions.fsx" 
#load @"include.system.runtime.interopservices.fsx" 
#load @"include.system.threading.fsx" 
#r "Microsoft.CSharp" 
printfn "microsoft.csharp Loaded" 