#load @"include.system.collections.fsx" 
#load @"include.system.diagnostics.debug.fsx" 
#load @"include.system.globalization.fsx" 
#load @"include.system.linq.fsx" 
#load @"include.system.resources.resourcemanager.fsx" 
#load @"include.system.runtime.fsx" 
#load @"include.system.runtime.extensions.fsx" 
#load @"include.system.threading.fsx" 
#r "../../../packages/System.Collections.Immutable/lib/netstandard1.0/System.Collections.Immutable.dll" 
printfn "system.collections.immutable Loaded" 