#load @"include.system.collections.fsx" 
#load @"include.system.diagnostics.debug.fsx" 
#load @"include.system.resources.resourcemanager.fsx" 
#load @"include.system.runtime.fsx" 
#load @"include.system.runtime.extensions.fsx" 
#r "System.Core" 
printfn "system.linq Loaded" 