#load @"include.system.collections.fsx" 
#load @"include.system.globalization.fsx" 
#load @"include.system.resources.resourcemanager.fsx" 
#load @"include.system.runtime.fsx" 
#load @"include.system.runtime.extensions.fsx" 
#load @"include.system.threading.fsx" 
#r "System" 
printfn "system.text.regularexpressions Loaded" 