#load @"include.system.collections.fsx" 
#load @"include.system.diagnostics.debug.fsx" 
#load @"include.system.resources.resourcemanager.fsx" 
#load @"include.system.runtime.fsx" 
#load @"include.system.threading.fsx" 
#r "System" 
printfn "system.objectmodel Loaded" 