#load @"include.system.collections.fsx" 
#load @"include.system.diagnostics.debug.fsx" 
#load @"include.system.globalization.fsx" 
#load @"include.system.io.fsx" 
#load @"include.system.io.filesystem.fsx" 
#load @"include.system.io.filesystem.primitives.fsx" 
#load @"include.system.resources.resourcemanager.fsx" 
#load @"include.system.runtime.fsx" 
#load @"include.system.runtime.extensions.fsx" 
#load @"include.system.runtime.interopservices.fsx" 
#load @"include.system.text.encoding.fsx" 
#load @"include.system.text.encoding.extensions.fsx" 
#load @"include.system.text.regularexpressions.fsx" 
#load @"include.system.threading.tasks.fsx" 
#load @"include.system.threading.tasks.extensions.fsx" 
#r "System.Xml" 
printfn "system.xml.readerwriter Loaded" 