#load @"include.system.collections.fsx" 
#load @"include.system.collections.immutable.fsx" 
#load @"include.system.collections.immutable.fsx" 
#load @"include.system.diagnostics.debug.fsx" 
#load @"include.system.io.fsx" 
#load @"include.system.linq.fsx" 
#load @"include.system.reflection.fsx" 
#load @"include.system.reflection.extensions.fsx" 
#load @"include.system.reflection.primitives.fsx" 
#load @"include.system.resources.resourcemanager.fsx" 
#load @"include.system.runtime.fsx" 
#load @"include.system.runtime.extensions.fsx" 
#load @"include.system.runtime.interopservices.fsx" 
#load @"include.system.text.encoding.fsx" 
#load @"include.system.text.encoding.extensions.fsx" 
#load @"include.system.threading.fsx" 
#r "../../../packages/System.Reflection.Metadata/lib/netstandard1.1/System.Reflection.Metadata.dll" 
printfn "system.reflection.metadata Loaded" 