#load @"include.system.io.fsx" 
#load @"include.system.reflection.fsx" 
#load @"include.system.reflection.emit.ilgeneration.fsx" 
#load @"include.system.reflection.primitives.fsx" 
#load @"include.system.runtime.fsx" 
printfn "system.reflection.emit Loaded" 